[project]
name = "eleventh"
version = "0.1.0"
description = "Turn-based card game inspired by FIFA's Utimate Team cards and the strategic style of Soccer Manager."
authors = [
    {name = "RickBarretto",email = "78623871+RickBarretto@users.noreply.github.com"}
]
license = {text = "MPL 2.0"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
