[package]
name = "quickapi"
version = "0.1.0"
edition = "2021"

[lib]
name = "quickapi"
path = "src/lib.rs"

[dependencies]
speculate = "0.1.2"
tokio = { version = "1.39", features = ["full"] }
async-trait = "0.1"
regex = "1.9"
serde_json = "1.0"
url = "2.3"
